[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "EasyFEA"
version = "0.1.0"
description = "User-friendly Python library that simplifies finite element analysis"
authors = [
    {name = "Matthieu Noel", email = "matthieu.noel7@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
keywords = ["finite-element-analysis", "phase-field", "python", "easy"]
license = {text = "MIT"}
classifiers = [    
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: MIT License",
    "Operating System :: :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyvista",
    "gmsh>=4.12.0",
    "numba",
    "pandas",
]

[project.optional-dependencies]
fast = [
    "pypardiso",
    "petsc", "petsc4py"
]

[project.urls]
"Source Code" = "https://github.com/matnoel/EasyFEA"

[tool.setuptools.packages.find]
include = [
    "EasyFEA",
    "EasyFEA.*",
    "examples",
    "examples.*",
]
# exclude = [
#     "FCBA",
#     "FCBA.*",
# ]